### ISSUE TITLE
GitLab Integration

### ISSUE THREAD

**Issue by FelixTJDietrich** [ls1intum/Hephaestus#140]
## Objective

As follow-up on #139. This integration will allow Hephaestus users to manage GitLab-based workspaces in the same way as GitHub-based workspaces, providing a unified experience across identity providers. 

## Tasks

- [ ] Integrate GitLab Rest API
  - [ ] Setup API Client
  - [ ] Sync entities
    - [ ] Issue
    - [ ] Issue comment
    - [ ] Label
    - [ ] Milestone
    - [ ] Merge request
    - [ ] Merge request review
    - [ ] Merge request review comment
    - [ ] Repository
    - [ ] User
- [ ] Integrate GitLab Webhooks
  - [ ] Setup Webhooks with the webhook ingest service (id = `gitlab-lrz`)
  - [ ] Process entities
    - [ ] Issue
    - [ ] Issue comment
    - [ ] Label
    - [ ] Milestone
    - [ ] Merge request
    - [ ] Merge request review
    - [ ] Merge request review comment
    - [ ] Repository
    - [ ] User
