### ISSUE TITLE
Legend for the Leaderboard

### ISSUE THREAD

**Issue by GODrums** [ls1intum/Hephaestus#159]
**Is your feature request related to a problem? Please describe.**
Currently, it might not be obvious what a certain icon from the leaderboard refers to or how the score is calculated. Additionally, the score calculation should match the old algorithm's results more closely.

**Describe the solution you'd like**
We want to provide a legend for the leaderboard, explaining icon and the score calculation, to make sure all developers understand the details of the leaderboard. The score algorithm further requires adaptations in regards to the newly available data, such as code comments, to more closely match the effort invested into a review.

**Tasks**

- [ ] Adjust Score Calculation
  - [ ] Reduce impact of comments on own PRs
  - [ ] Cap points gained by code comments to foster manual reviews
- [ ] Display points for individual reviews on the profile page
- [ ] Add legend below leaderboard (#165)
  - [ ] Explain leaderboard icons
  - [ ] Summarize score calculation algorithm

**Describe alternatives you've considered**
None

**Additional context**
Requested by Stephan

**Comment by FelixTJDietrich** [comment]
We will adjust the score calculation in a separate PR, I will just close this issue now.
