### ISSUE TITLE
`Admin Page`: Completing initial functionality

### ISSUE THREAD

**Issue by GODrums** [ls1intum/Hephaestus#160]
Follow-Up for #124 

**Tasks**
- [ ] Rework "Repositories to Monitor" UI with list
- [ ] Improve `/admin/teams`
  - [ ] Editable team color
  - [ ] Removable team labels + list to chose label from
