### ISSUE TITLE
Require login for using Hephaestus

### ISSUE THREAD

**Issue by FelixTJDietrich** [ls1intum/Hephaestus#163]
### Motivation

In preparation of workspaces, see #139, we need to always authenticate users since a user should only see their own workspaces. This also gives us more insights into how users use Hephaestus and allows us to personalize it to the logged in user.

### Tasks

- [x] Create custom Keycloak theme ([Keycloakify](https://www.keycloakify.dev/)?)
- [x] Use custom Keycloak theme for development
- [x] Use custom Keycloak theme for production
- [x] Terms & conditions + privacy policy
- [x] Redirect to login if not logged in

**Comment by FelixTJDietrich** [comment]
Closed with #164
